//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop_watch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Binh_luan
    {
        public int Id_binh_luan { get; set; }
        public Nullable<int> Id_san_pham { get; set; }
        public Nullable<int> Id_tai_khoan_kh { get; set; }
        public string Noi_dung { get; set; }
        public Nullable<System.DateTime> Ngay_tao { get; set; }
        public Nullable<int> Id_tai_khoan_Ad { get; set; }
        public string Tra_loi_binh_luan { get; set; }
        public Nullable<System.DateTime> Ngay_cap_nhat { get; set; }
    
        public virtual San_pham San_pham { get; set; }
        public virtual Tai_khoan_Kh Tai_khoan_Kh { get; set; }
        public virtual Tai_khoan_Ad Tai_khoan_Ad { get; set; }
    }
}
