//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop_watch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class San_pham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public San_pham()
        {
            this.Don_hang = new HashSet<Don_hang>();
            this.Binh_luan = new HashSet<Binh_luan>();
        }
    
        public int Id_san_pham { get; set; }
        public string Ten_san_pham { get; set; }
        public string Hinh_anh { get; set; }
        public Nullable<byte> Loai_san_pham { get; set; }
        public int Gia_goc { get; set; }
        public Nullable<int> Gia_sale { get; set; }
        public Nullable<int> So_luong { get; set; }
        public string Nguoi_cap_nhat { get; set; }
        public Nullable<System.DateTime> Ngay_Cap_nhat { get; set; }
        public string Mo_ta_ngan { get; set; }
        public string Mo_ta_dai { get; set; }
        public string Chu_thich { get; set; }
        public Nullable<byte> Trang_thai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Don_hang> Don_hang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Binh_luan> Binh_luan { get; set; }
    }
}
