//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop_watch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tin_tuc
    {
        public int Id_Tintuc { get; set; }
        public string Ten_tin_tuc { get; set; }
        public string Hinh_anh { get; set; }
        public string Nguoi_cap_nhat { get; set; }
        public Nullable<System.DateTime> Ngay_Cap_nhat { get; set; }
        public string Chu_thich { get; set; }
        public Nullable<byte> Trang_thai { get; set; }
        public string Noi_dung { get; set; }
    }
}
