//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop_watch.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Shop_watchEntities : DbContext
    {
        public Shop_watchEntities()
            : base("name=Shop_watchEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<San_pham> San_pham { get; set; }
        public virtual DbSet<Tai_khoan_Ad> Tai_khoan_Ad { get; set; }
        public virtual DbSet<Tai_khoan_Kh> Tai_khoan_Kh { get; set; }
        public virtual DbSet<Don_hang> Don_hang { get; set; }
        public virtual DbSet<Binh_luan> Binh_luan { get; set; }
        public virtual DbSet<Tin_tuc> Tin_tuc { get; set; }
    }
}
